// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeootmgutepjsivmzblw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlb290bWd1dGVwanNpdm16Ymx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDU5OTcsImV4cCI6MjA2NjkyMTk5N30.BXLXZz6qW5ZXUXX6ArfegTDJ8b7RpYg0zyf5WZUCGZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});